main: com.kyloka.splashAndSpat.Main
version: 1.0
name: SplashAndSplat
description: You splash, if you miss you splat

commands:
  ssjoin:
    description: join SplashOrSplat
  sspos1:
    description: lmao
  sspos2:
    description: ayy
  ssstart:
    description: ayy
  ssstop:
    description: lmao
  ssreset:
    description: hai
  ssleave:
    description: leave the current game